import type { Metadata } from 'next';
import { AppShell } from '@/components/dashboard/app-shell';
import { Card } from '@/components/ui/card';

export const metadata: Metadata = {
  title: 'About | Supply Chain Pulse',
  description: 'Why Supply Chain Pulse exists and how its provider-based architecture works.'
};

export default function AboutPage() {
  return (
    <AppShell>
      <section>
        <h1 className="text-3xl font-semibold text-cyan-100">About Supply Chain Pulse</h1>
        <p className="mt-2 max-w-3xl text-sm text-slate-300">Supply Chain Pulse is a public logistics intelligence dashboard designed for fast operational awareness across vessels, ports, and disruption signals.</p>
      </section>
      <section className="grid gap-4 md:grid-cols-2">
        <Card className="p-5">
          <h2 className="text-lg font-semibold text-white">What it combines</h2>
          <ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-slate-300">
            <li>Map-first vessel movement and trade route visibility</li>
            <li>Port congestion scoring and queue depth ranking</li>
            <li>Weather-linked disruption risk with logistics implications</li>
            <li>Public webcam intelligence for real-world port conditions</li>
            <li>Daily briefs generated by LLM or deterministic templates</li>
          </ul>
        </Card>
        <Card className="p-5">
          <h2 className="text-lg font-semibold text-white">How reliability is handled</h2>
          <p className="mt-3 text-sm text-slate-300">Provider adapters isolate each data feed. If live keys are unavailable, the platform automatically falls back to typed sample datasets so every module remains usable locally and in demos.</p>
        </Card>
      </section>
    </AppShell>
  );
}
